export const stateList = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

/* export const cityList = [
  "Ahmedabad",
  "Bangalore",
  "Chandigarh",
  "Chennai",
  "Delhi",
  "Gurgaon",
  "Hyderabad",
  "Kolkata",
  "Mumbai",
  "Noida",
  "Pune",
  "Agra",
  "Ahmednagar",
  "Ajmer",
  "Aligarh",
  "Allahabad",
  "Alwar",
  "Ambala",
  "Amravati",
  "Amritsar",
  "Anand",
  "Aurangabad",
  "Bankura",
  "Bareilly",
  "Belgaum",
  "Berhampur",
  "Bhatinda",
  "Bhavnagar",
  "Bhopal",
  "Bhubaneswar",
  "Bikaner",
  "Bilaspur",
  "Burdwan",
  "Coimbatore",
  "Cuttack",
  "Dehradun",
  "Erode",
  "Faridabad",
  "Gandhinagar",
  "Ghaziabad",
  "Gorakhpur",
  "Greater Noida",
  "Guntur",
  "Guwahati",
  "Gwalior",
  "Hugli",
  "Indore",
  "Jabalpur",
  "Jaipur",
  "Jalandhar",
  "Jalgaon",
  "Jammu",
  "Jhansi",
  "Jodhpur",
  "Kakinada",
  "Kanpur",
  "Kanyakumari",
  "Kochi",
  "Kolhapur",
  "Kollam",
  "Kota",
  "Kottayam",
  "Kurnool",
  "Kurukshetra",
  "Lucknow",
  "Ludhiana",
  "Madurai",
  "Mangalore",
  "Mathura",
  "Meerut",
  "Mohali",
  "Moradabad",
  "Murshidabad",
  "Muzaffarpur",
  "Mysore",
  "Nagpur",
  "Nashik",
  "Patiala",
  "Patna",
  "Raipur",
  "Rajkot",
  "Ranchi",
  "Rewa",
  "Rohtak",
  "Saharanpur",
  "Salem",
  "Sangli",
  "Satara",
  "Satna",
  "Secunderabad",
  "Solapur",
  "Sonepat",
  "Surat",
  "Thane",
  "Thiruvananthapuram",
  "Thrissur",
  "Tirupathi",
  "Trichy",
  "Udaipur",
  "Ujjain",
  "Varanasi",
  "Vellore",
  "Vijayawada",
  "Visakhapatnam",
  "Warangal",
  "Yamuna Nagar",
]; */

export const cityList = [
  "Bengaluru",
  "Bhubaneswar",
  "Chennai",
  "Coimbatore",
  "Guwahati",
  "Hyderabad",
  "Indore",
  "Jaipur",
  "Karad",
  "Kochi",
  "Kolkata",
  "Mohali",
  "Mumbai",
  "Nagpur",
  "Nashik",
  "New Delhi",
  "Noida",
  "Patna",
  "Pune",
  "Ranchi",
  "Silchar",
  "Thiruvananthapuram",
];

export const regionList = ["Bengaluru", "Hyderabad", "Mumbai", "Noida", "Pune"];

export const branchList = [
  "Computer Science & Engineering",
  "Mechanical Engineering",
  "Electronics & Communication Engineering",
  "Civil Engineering",
  "Electrical & Electronics Engineering",
  "Information Technology",
  "Electrical Engineering",
  "Electronics & Instrumentation Engineering",
  "Chemical Engineering",
  "Automobile Engineering",
  "Electronics & Telecommunication Engineering",
  "Bio Technology",
  "Aeronautical Engineering",
  "Computer Engineering",
  "Bio-Medical Engineering",
  "Electronics & Computer Engineering",
  "Industrial & Production Engineering",
  "Mechatronics Engineering",
  "Agricultural Engineering",
  "Food Technology",
  "Mining Engineering",
  "Petroleum Engineering",
  "Aerospace Engineering",
  "Electronics",
  "Computer Science and Engineering",
  "Production Engineering",
  "Electronics and Communication Engineering",
  "Environmental Engineering",
  "Metallurgical Engineering",
];

const centersList = [
  {
    id: 1,
    name: "C-DAC Advanced Computing Training School",
    nick: "CDAC ACTS Headquarters",
    address: {
      street: "C-DAC Innovation Park Sr. No. 34/B/1 Panchvati",
      area: "Pashan",
      cityId: 1,
      city: "Pune",
      state: "Maharashtra",
      stateCode: "MH",
      pincode: "411008",
    },
    courses: [
      "PG-DAC",
      "PG-DVLSI",
      "PG-DESD",
      "PG-DITISS",
      "PG-DAI",
      "PG-DBDA",
      "PG-DIoT",
      "PG-DHPCSA",
      "e-DAC",
      "e-DBDA",
    ],
    contact: {
      phone: ["18008430222"],
      person: "Mr. Parimal Wagh",
      email: ["acts@cdac.in"],
    },
  },
  {
    id: 2,
    name: "C-DAC Advanced Computing Training School",
    nick: "CDAC Knowledge Park",
    address: {
      street: "No.1, Old Madras Road Above Bank of Mysore, Near NGEF",
      area: "Knowledge Park",
      cityId: 2,
      city: "Bengaluru",
      state: "Karnataka",
      stateCode: "KA",
      pincode: "560038",
    },
    courses: ["PG-DAC", "PG-DESD", "PG-DBDA", "PG-DIoT", "e-DAC", "e-DBDA"],
    contact: {
      phone: ["66116400", "66116401", "66116402", "66116403", "080-66116560"],
      person: "Binu George & M Savithri",
      email: ["acts@cdac.in"],
    },
  },
  {
    id: 3,
    name: "C-DAC Advanced Computing Training School",
    nick: "CDAC E-City",
    address: {
      street:
        "No. 68, 4th Cross, Electronic City Phase 1, Hosur Road, Opp.BSNL Telephone Exchange",
      area: "Electronic City Phase 1",
      cityId: 2,
      city: "Bengaluru",
      state: "Karnataka",
      stateCode: "KA",
      pincode: "560100",
    },
    courses: ["PG-DAC", "PG-DITISS", "e-DAC"],
    contact: {
      phone: ["+91-80-28523300"],
      person: "Ms Reshma (Admission), Mr Mohamed Ashfaqu(Hostel)",
      email: ["course_blrec@cdac.in", "mohammad@cdac.in"],
    },
  },
  {
    id: 4,
    name: "Lakshya",
    nick: "CDAC Bhubaneshwar",
    address: {
      street: "4th Floor, IDCO Towers, 1 Janpath",
      area: "Janpath Rd",
      cityId: 3,
      city: "Bhubaneswar",
      state: "Odisha",
      stateCode: "OR",
      pincode: "751022",
    },
    courses: ["PG-DAC", "PreDAC"],
    contact: {
      phone: ["0674-2542520", "9040022750"],
      person: "Alok Mishra",
      email: ["lakshya@lakshyatraining.org"],
    },
  },
  {
    id: 5,
    name: "C-DAC Advanced Computing Training School",
    nick: "CDAC Chennai",
    address: {
      street:
        "'TIDEL Park', 8th Floor,'D' Block (North), No.4, Rajiv Gandhi Salai, Taramani",
      area: "Taramani",
      cityId: 4,
      city: "Chennai",
      state: "Tamilnadu",
      stateCode: "TN",
      pincode: "600113",
    },
    courses: ["PG-DAC", "PG-DESD", "PG-DBDA", "PG-DIoT", "e-DAC", "e-DBDA"],
    contact: {
      phone: ["044-22540028", "22542226", "22542227"],
      person: "Ms.SUNANDHA D",
      email: ["chnacts@cdac.in"],
    },
  },
  {
    id: 6,
    name: "Amrita Institute of Advanced Computing",
    nick: "CDAC Coimbatore",
    address: {
      street: "Ettimadai Post Coimbatore",
      area: "Coimbatore",
      cityId: 5,
      city: "Coimbatore",
      state: "Tamilnadu",
      stateCode: "TN",
      pincode: "641105",
    },
    courses: ["e-DAC"],
    contact: {
      phone: ["0422–2656422"],
      person: "Mr. M. Sreevalsan",
      email: ["aiac@amrita.edu"],
    },
  },
  {
    id: 7,
    name: "C-DACs - Advanced Computing Training School",
    nick: "CDAC Guwahati",
    address: {
      street: "GUIST Guwahati University OR Assam Don Bosco University",
      area: "Guwahati",
      cityId: 6,
      city: "Guwahati",
      state: "Assam",
      stateCode: "AS",
      pincode: "782402",
    },
    courses: ["PG-DAC"],
    contact: {
      phone: ["03842-242009"],
      person: "",
      email: ["selva@cdac.in"],
    },
  },
  {
    id: 8,
    name: "C-DACs - Advanced Computing Training School",
    nick: "CDAC Hyderabad",
    address: {
      street:
        "Plot No. 6 & 7, Hardware Park, Sy No. 1/1, Srisailam Highway, Pahadi Shareef Via Keshavagiri (Post)",
      area: "Srisailam Highway",
      cityId: 7,
      city: "Hyderabad",
      state: "Andhra Pradesh",
      stateCode: "AP",
      pincode: "500016",
    },
    courses: [
      "PG-DAC",
      "PG-DVLSI",
      "PG-DESD",
      "PG-DITISS",
      "PG-DSSD",
      "PG-DASSD",
      "e-DAC",
    ],
    contact: {
      phone: ["040-23737127"],
      person: "Mr. Sharanabasappa , Senior Technical Officer",
      email: ["cdachyd@cdac.in"],
    },
  },
  {
    id: 9,
    name: "Orlando Academy",
    nick: "CDAC Indore",
    address: {
      street:
        "20-21 Press Complex, First Floor, Above Mahanagar Press,Behind Danik Bhaskar,A.B. Road",
      area: "A.B. Road",
      cityId: 8,
      city: "Indore",
      state: "Madhya Pradesh",
      stateCode: "MP",
      pincode: "452001",
    },
    courses: ["PG-DAC", "e-DAC"],
    contact: {
      phone: ["0731-4285004", "9584894999", "9009886261"],
      person: "Mr. Kunal Kansal",
      email: ["info@orlando.co.in"],
    },
  },
];
